services:
  api:
    image: ${API_IMAGE:-ghcr.io/vaibhav-singh2/task-manager-api:latest}
    container_name: task-manager-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - apps/api/.env

  web:
    image: ${WEB_IMAGE:-ghcr.io/vaibhav-singh2/task-manager-web:latest}
    container_name: task-manager-web
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - apps/web/.env
    depends_on:
      - api
