services:
  mongo:
    image: mongo:latest
    container_name: task-manager-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: task-manager
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: